a=int(input('Masukkan nilai a: '))
b=int(input('Masukkan nilai b: '))
i=int(input('Masukkan nilai i: '))
j=int(input('Masukkan nilai j: '))
x=int(input('Masukkan nilai x: '))
y=int(input('Masukkan nilai y: '))

h=(a-b)*i/j-(x+y)
print('\nHasil dari a dikurang b dikali i dibagi j dikurang dengan x ditambah y adalah ',end='')
print('%.3f' %h)